services:

# build service 1
  service1:
    build:
      context: ./components/service1
      dockerfile: Dockerfile
    volumes:
      - ./components/service1:/var/tempData
    networks:
      - network_app_service1
      - network_multi
    depends_on:
      - postgreDB_service1

  postgreDB_service1:
    image: postgres:14-alpine
    container_name: postgreDB_service1
    restart: unless-stopped
    environment:
      - DB_HOST=postgreDB_service1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5433:5432'
    volumes:
      - ./components/service1/postgresql:/var/lib/postgresql/data
    networks:
      - network_app_service1


# build service 2
  service2:
    build: 
      context: ./components/service2
      dockerfile: Dockerfile
    volumes:
      - ./components/service2:/var/tempData
    networks:
      - network_app_service2
      - network_multi
  

  postgreDB_service2:
    image: postgres:14-alpine
    container_name: postgreDB_service2
    restart: unless-stopped
    environment:
      - DB_HOST=postgreDB_service2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5431:5432'
    volumes:
        - ./components/service2/postgresql:/var/lib/postgresql/data
    networks:
      - network_app_service2

networks:
  network_app_service1:
    driver: bridge
  network_app_service2: 
    driver: bridge
  network_multi:
    driver: bridge